title: <p align="center"> Pooja dalvi </p>
logo: /assets/img/poojadalvi.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/pooja-dalvi-06142415b/">LinkedIn</a> |
  <a href="https://github.com/beingpooja">GitHub</a>
  
  <br>   
  I'm Learning on machine learning and AL.
  I am working as Frontend Developer.
  I have experienced of 2.5 yrs in Frontend Development
  <br>
  </p>
theme: jekyll-theme-minimal
