title: <p align="center"> Pooja dalvi </p>
logo: /assets/img/pooja_dalvi.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/pooja-dalvi-06142415b/">LinkedIn</a> |
  <a href="https://github.com/beingpooja">GitHub</a>
  
  <br>   
  I'm Learning  Machine Learning and AL.
  Magento Frontend Developer | Bigcommerce Developer | UI Developer
  with 2.5 yrs of ecperienced in Frontend Development
  <br>
  </p>
theme: jekyll-theme-minimal
